### ISSUE TITLE
Script for simulating coupling on CARC

### ISSUE THREAD

**Issue by agregory65** [VirtualWatershed/vw-ripcas-dflow#5]
![img_0953](https://cloud.githubusercontent.com/assets/7781871/14479410/61076d20-00db-11e6-90ad-9607505d3905.jpg)

**Comment by agregory65** [comment]
![img_0956](https://cloud.githubusercontent.com/assets/7781871/14479433/aed5530a-00db-11e6-9ff6-71409a858e1d.jpg)

**Comment by mtpain** [comment]
see also Sarah's styled diagram

[Work_Flow_mockup_v1.pptx](https://github.com/VirtualWatershed/vw-jemez/files/217741/Work_Flow_mockup_v1.pptx)

**Comment by agregory65** [comment]
Example Files

Queuing a run on CARC: This usually ends in .pbs
[dflow_mpi.txt](https://github.com/VirtualWatershed/vw-ripcas-dflow/files/221406/dflow_mpi.txt)

Boundary Conditions:
We will have .pol files but cmp's are the one that change.  These below are .cmp's.
[boundriverdown_0001.txt](https://github.com/VirtualWatershed/vw-ripcas-dflow/files/221408/boundriverdown_0001.txt)
[boundriver_up_0001.txt](https://github.com/VirtualWatershed/vw-ripcas-dflow/files/221410/boundriver_up_0001.txt)

.EXT files
[jemez_r02_boundary.txt](https://github.com/VirtualWatershed/vw-ripcas-dflow/files/221413/jemez_r02_boundary.txt)

.MDU File
[jem_new.txt](https://github.com/VirtualWatershed/vw-ripcas-dflow/files/221411/jem_new.txt)

**Comment by mtpain** [comment]
@agregory65 In the .EXT file I see .pli extensions on what appear to be the boundary condition files, but no .cmp or .pol files. Does the EXT file need to point to boundary condition files? What is this one pointing to (see below)?

```
QUANTITY=dischargebnd
FILENAME=boundriver_up.pli
FILETYPE=9
METHOD=3
OPERAND=O

QUANTITY=waterlevelbnd
FILENAME=boundriverdown.pli
FILETYPE=9
METHOD=3
OPERAND=O

QUANTITY=frictioncoefficient
FILENAME=veg-out.pol
FILETYPE=10
METHOD=4
OPERAND=O
```

**Comment by agregory65** [comment]
DFLOW requires both .pli and .cmp, but the .ext only needs to point to the .pli- has something to do with the naming convention I think.  Also, the .cmp's will need to retain their original name.

**Comment by mtpain** [comment]
Ok, thanks. Is there a place in the DFLOW input files where the .cmp files are referenced? Or should it be the same as the .pli, just with a different extension? Can you please share the .pli files? It seems those will have to go along to the DFLOW input directory?

One more related question about DFLOW files, where is the output file name specified?

**Comment by mtpain** [comment]
nm about the example .pli files, I see them in some data you shared a while back, sorry! 

Still curious about how to specify output, though. Thanks!
