### ISSUE TITLE
Calculate Boundary Conditions Using Mannings 2D solver

### ISSUE THREAD

**Issue by agregory65** [VirtualWatershed/vw-ripcas-dflow#6]
Sent excel spreadsheet named "Boundary Condition Points" on 4/5 that calculates flow based on channel geometry at outlet.  This will need to be written in python.  Input should be channel geometry, mannings n and the interval to run calculation on from min to max elevations in channel.  Output will be a vector of flows corresponding to each water surface elevation the flow was calculated for.

**Comment by mtpain** [comment]
1. Calculate flow for each of the increments from min to max
2. Plug in calculated flow with flow and elevation that most closely correspond to flood event
3. Minimize the absolute difference between calculated flows and flows from flood or find where less than 5% difference taken with historical flows

**Comment by agregory65** [comment]
Mannings Calculator requires inputs of channel geometry, mannings n and slope.  Channel geometry data must be ordered from left to right or vice versus.  Water surface elevation (WSE) is associated with Z value in geometry file and is to be calculated from minimum elevation to the lower elevation of the end points.

Steps for calculating Discharge in cms for one water surface elevation:
1. Calculate Euclidean distance between each point using only X and Y components.

2. For each set of points determine the min and max value so that you do not have to deal with sign issues later.

3. Determine if the WS is located above, between, or below each set of points.  If the flow is above both channel bottom points it is called trap (for trapezoidal calculation).  If the flow is between the two channel bottom points, it will be called a trap.

4.  Using the information gleaned in step 1,2 and 3, we determine the area and WP between the WSE and channel bottom points.   WP is the wetted part of the channel bottom.

5. Take sums of WP and Area, call them TWP, and TA respectively.

6. Calculate mannings, n is roughness and S is channel slope:  Q = (1/n )* (S^1/2) * TA * ((TA/TWP)^2/3)

[ConceptualFlow.pptx](https://github.com/VirtualWatershed/vw-ripcas-dflow/files/221340/ConceptualFlow.pptx)
[Control.txt](https://github.com/VirtualWatershed/vw-ripcas-dflow/files/221341/Control.txt)
[peak.txt](https://github.com/VirtualWatershed/vw-ripcas-dflow/files/221342/peak.txt)
[DBC_geometry.txt](https://github.com/VirtualWatershed/vw-ripcas-dflow/files/221346/DBC_geometry.txt)

**Comment by mtpain** [comment]
A couple questions

1. Is the Control file here is something new that we will add? Are you thinking we'll read the n value and slope from this file?

2. Can you please remind me how the upstream boundary condition is assigned?

**Comment by mtpain** [comment]
I think there was an error in the calculation of flow rate. See below. The formula you had was 

```
=(1/F2)*L44*((L44/N44)^2/3)*SQRT(I1)
```

It should be

```
=(1/F2)*L44*((L44/N44)^(2/3))*SQRT(I1)
```

**Comment by agregory65** [comment]
Your'e right thanks
